import "./globals.css";
import { Providers } from "@/redux/provider";
import Topbar from "../../components/Topbar/page"
import { Poppins } from 'next/font/google';
import Header from "../../components/Header/page";
import Footer from "../../components/Footer/page";
export const metadata = {
  title: "Ecommerce App Demo",
  description: "Generated by create next app",
};

// If loading a variable font, you don't need to specify the font weight
const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={poppins.className}>
     
        <Topbar/>
        <Header/>
        <Providers>{children}</Providers>
        <Footer/>
       
      </body>
    </html>
  );
}
